# Theme settings
doks:
    baseurl: /fnn-web/
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: "FNN: Realtime Benchmark"
            image: false
        nav:
            - item_name: API
              item_url: 'https://fnn.docs.apiary.io/'
            - item_name: Docs
              item_url: '/documentation'
            - item_name: Manifesto
              item_url: '/manifesto'
    footer:
        content:
            logo:
                text: 
                image: true
            copyright: "FNN: Realtime Benchmark"
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
