# Theme settings
api_url: https://factbench-api.now.sh
doks:
    baseurl: ""
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Realtime Fact Benchmark
            image: false
        nav:
            - item_name: How it works
              item_url: '/how'
            - item_name: Model
              item_url: '/model' 
            - item_name: Join the trial 
              item_url: '/trial' 
            - item_name: Documentation
              item_url: '/documentation'
            - item_name: Manifesto
              item_url: '/manifesto'
            - item_name: About us
              item_url: '/about'              
    footer:
        nav:
            - item_name: How it works
              item_url: '/how'
            - item_name: Model
              item_url: '/model' 
            - item_name: Join the trial 
              item_url: '/trial' 
            - item_name: Documentation
              item_url: '/documentation'
            - item_name: Manifesto
              item_url: '/manifesto'
            - item_name: About us
              item_url: '/about'    
        content:
            logo:
                text: 
                image: true
            copyright: "Fact Benchmark"
    google_analytics:
        tracking_code: "UA-134277708-1" # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./theme/_layouts
includes_dir: ./theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
