# Theme settings
api_url: https://factbench-api.now.sh
doks:
    baseurl: ""
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Fact Benchmark
            image: false
        nav:
            - item_name: Docs
              item_url: '/documentation'
            - item_name: Manifesto
              item_url: '/manifesto'
    footer:
        content:
            logo:
                text: 
                image: true
            copyright: "Factcheck Benchmark"
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./theme/_layouts
includes_dir: ./theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
